# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillci" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "76007b8789e348abf1c22395d6d2f64601a7e43ac37bf48c792450062ac15255"
      url "https://github.com/kabirnarang39/skillci/releases/download/v#{version}/skillci_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "25bf584d2914c2251bedaae1788ef45aa6905f4cc84b9bc6c0c2c41ce8547129"
      url "https://github.com/kabirnarang39/skillci/releases/download/v#{version}/skillci_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c14256846b95721b9c6defcf11a3f4cde0d215bd635be95816527bf29c8b0e1"
      url "https://github.com/kabirnarang39/skillci/releases/download/v#{version}/skillci_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ae16ab997bf24c6c451b6d0fecf6780cdd01051b281b00e6fa425f78834adbc"
      url "https://github.com/kabirnarang39/skillci/releases/download/v#{version}/skillci_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skillci"
  desc "Lint, eval, and regression-test Claude Skills against a model matrix"
  homepage "https://github.com/kabirnarang39/skillci"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillci"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skillci"]
    end
  end

  # No zap stanza required

end
