# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillci" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "ab8fc60c64ad2bf08243c24b7d5289e38f7cd7d1e2cafccfceacbc8e59eeef84"
      url "https://github.com/kabirnarang39/skillci/releases/download/v#{version}/skillci_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ee73e876ef45e051d0fab2b7ff3bfc9031bb1d12c39ece60c9abb2c4f7622b8"
      url "https://github.com/kabirnarang39/skillci/releases/download/v#{version}/skillci_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "17625982685213c3639830cbec0bb206e393cebfdd5ab5855f07e869de566718"
      url "https://github.com/kabirnarang39/skillci/releases/download/v#{version}/skillci_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f12b11b1141f035e0a956eb7c353eaec0c965ae17c363b50ac19207bd8bc45ff"
      url "https://github.com/kabirnarang39/skillci/releases/download/v#{version}/skillci_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skillci"
  desc "Lint, eval, and regression-test Claude Skills against a model matrix"
  homepage "https://github.com/kabirnarang39/skillci"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillci"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skillci"]
    end
  end

  # No zap stanza required

end
