# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillci" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "389a63cf4495e575df76a6ce10b6ca651094dd2f01a21cc47ebe0fb4387f6f63"
      url "https://github.com/kabirnarang39/skillci/releases/download/v#{version}/skillci_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e48e8094704806fb48835d94e252fd01fbeca37e1c56796abf0a8d28719ea67e"
      url "https://github.com/kabirnarang39/skillci/releases/download/v#{version}/skillci_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e2abe9e4388614bc78e60e3dcd02360d385bedb9d716f4a921dc37b8c756efa6"
      url "https://github.com/kabirnarang39/skillci/releases/download/v#{version}/skillci_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa177c48586169a67e710c17bd4b37898b432dd610df87c4ed7723206cae560c"
      url "https://github.com/kabirnarang39/skillci/releases/download/v#{version}/skillci_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skillci"
  desc "Lint, eval, and regression-test Claude Skills against a model matrix"
  homepage "https://github.com/kabirnarang39/skillci"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillci"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skillci"]
    end
  end

  # No zap stanza required

end
